/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.184.0Release
// Tag = production/release/21.184.0-0-gb0e3606
/////////////////////////////////////////////////////////////////////////////////////////////

public enum AutolapTrigger: UInt8, CaseIterable, Sendable {
    case time = 0
    case distance = 1
    case positionStart = 2
    case positionLap = 3
    case positionWaypoint = 4
    case positionMarked = 5
    case off = 6
    case autoSelect = 13
    case invalid = 0xFF
}
