/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.184.0Release
// Tag = production/release/21.184.0-0-gb0e3606
/////////////////////////////////////////////////////////////////////////////////////////////

public enum IndoorBikeExerciseName: UInt16, CaseIterable, Sendable {
    case airBike = 0
    case assaultBike = 1
    case stationaryBike = 3
    case invalid = 0xFFFF
}
