/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.184.0Release
// Tag = production/release/21.184.0-0-gb0e3606
/////////////////////////////////////////////////////////////////////////////////////////////

public enum RunExerciseName: UInt16, CaseIterable, Sendable {
    case run = 0
    case walk = 1
    case jog = 2
    case sprint = 3
    case runOrWalk = 4
    case speedWalk = 5
    case warmUp = 6
    case invalid = 0xFFFF
}
