/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2025 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.184.0Release
// Tag = production/release/21.184.0-0-gb0e3606
/////////////////////////////////////////////////////////////////////////////////////////////

public enum TimeMode: UInt8, CaseIterable, Sendable {
    case hour12 = 0
    case hour24 = 1
    case military = 2
    case hour12WithSeconds = 3
    case hour24WithSeconds = 4
    case utc = 5
    case invalid = 0xFF
}
